### ISSUE TITLE
Don't contact SysAdmins via the wiki?

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/owg-website#33]
We mention the system admins a few times in the [Tile Usage Policy](https://github.com/openstreetmap/owg-website/blob/0e77e3d5b406092f06f10ad7d3bf000fd7587104/policies/tiles.md) and possibly elsewhere in the policies. Should we change that to OWG?

In the past, such decisions may have been made on the basis of the current load on the system. But I feel like nowadays OWG aims to have a more predictable policy-based framework for these kinds of things. Additionally, contacting individual admins via their wiki pages is probably a hit-and-miss process on a good day, and these things would be better directed to an email alias or something similar which can be handled by a group of people.

**Comment by gravitystorm** [comment]
I'd be happy to see it being changed to OWG - I agree that it's developed into more of a policy thing nowadays. 

If we choose to keep the contact as the sysadmins, we should point people directly to an email address, rather than to a wiki page, which doesn't even have a contact address on it.
