### ISSUE TITLE
Tile Usage Policy: can I cache them?

### ISSUE THREAD

**Issue by unilynx** [openstreetmap/owg-website#67]
Reading https://operations.osmfoundation.org/policies/tiles/ it's not clear to me if it's okay to cache them (eg put a nginx proxy in front of it), ie like a website that would directly load tiles, but rewriting the URLs to refer to my proxy first. There wouldn't be any precaching, so it wouldn't hit the servers any harder than simply having web browsers load them directly.

If it's allowed in principle (and I think it would be, it would only decrease load...) how should I interpret the technical requirements ?

> Valid HTTP User-Agent identifying application. Faking another app’s User-Agent WILL get you blocked.

Should I pass on the user's User-Agent, or should I have the proxy send a specific user-agent itself? (eg 'nginx') 

> If known, a valid HTTP Referer.

"valid" is not necessarily the actual referrer. I wouldn't have a problem just sending the origin of the website as a referrer (eg https://www.example.net/ if that's where the user sees the tiles) but sending the full url might leak some private data. Those considerations are no different than what I would set the `Referrer-Policy` header too of course.

> DO NOT send no-cache headers. (“Cache-Control: no-cache”, “Pragma: no-cache” etc.)

I'm pretty sure I can strip those headers, even if the browser itself does send them (shift-reload). 

> Cache Tile downloads locally according to HTTP Expiry Header, alternatively a minimum of 7 days.

Seems doable. I'm pretty sure nginx tries to do the right thing out of the box.

> Maximum of 2 download threads. (Unmodified web browsers’ download thread limits are acceptable.)

As I wouldn't be prefetching, there wouldn't be more download threads than if the users had connected directly. On the other hand, a mix of real users would be downloading a lot smoother (slower) than a proxyserver in a datacenter. But if I need to strictly enforce this limit, and the cache hit rate isn't high enough.. this might actually make a proxy solution slower than having users connect directly to the tile server and might not make it worth the effort. This would probably require seeing it in practice.

**Comment by tomhughes** [comment]
This is a bug tracker for the web site source, not an enquiry service. Please contact the [Operations Working Group](https://wiki.osmfoundation.org/wiki/Operations_Working_Group) if you have questions.
