### ISSUE TITLE
Website doesn't show recent posts

### ISSUE THREAD

**Issue by zorun** [openstreetmap/owg-website#89]
I tried to find the recent outage reports (such as 6fd72e793e24b4d2acd7b3818ddac240d5fd9444) on the website, but I cannot find them.

On the [main page](https://operations.osmfoundation.org/) the newest monthly report is July 2021, and on the [archive page](https://operations.osmfoundation.org/reports/) as well.

Maybe the website doesn't get updated properly?

**Comment by tomhughes** [comment]
It's not published yet - it will be linked from the next monthly report when that is published.

**Comment by danieldegroot2** [comment]
Related #90
